Viewのrenderにて、kaminari 利用時のエラー回避 ついでにstub_modelを、FactoryGirl 4.0用の書き方へ変更
参考サイト http://stackoverflow.com/questions/7080335/rspec-test-broken-by-pagination-kaminari
以下、エラー内容
  1) customers/index renders a list of customers
     Failure/Error: render
     ActionView::Template::Error:
       undefined method `current_page' for #<Array:0x4464780>
     # ./app/views/customers/index.html.erb:38:in `_app_views_customers_index_html_erb__605963508_35884632'
     # ./spec/views/customers/index.html.erb_spec.rb:13:in `block (2 levels) in <top (required)>'